### ISSUE TITLE
Move ecosystem fact sheets out of asset folder

### ISSUE THREAD

**Issue by jaydorsey** [rubyforgood/ghgvc#23]
These can live in the public folder, don't need to be anywhere near the asset pipeline

**Comment by VictoriaVasys** [comment]
Hi @jaydorsey , I'm a junior rails developer and have a BS in Atmospheric & Oceanic Sciences with a minor in Environmental studies; I'm really interested in this project and would love to help contribute! 

From the issues I've reviewed, it seems like you're very proactive with assigning people and keeping the repo up-to-date; if I'm interested in tackling an issue, is the best approach to request to be assigned through a comment on the issue? 

Regarding this issue in particular, are the fact sheets linked-to or stored anywhere on the live app or are they there solely as reference to the developers? I haven't been able to find any & the most relevant file I've found, public/data/maps/*_ecosystems.json, doesn't seem to have any corresponding data. 

If the above is true, I'm happy to simply move the directory to close this bug. If it is, however, intertwined with other functions, please let me know how best to find them.

Thanks!
Victoria

**Comment by jaydorsey** [comment]
@VictoriaVasys thanks for your interest. We'd love it if you wanted to help contribute!

If you want to work on something, you can just leave a comment on the ticket for now & I'll look at getting you added to the assignee list this week.

I'm not 100% sure everywhere these documents are used or the impact of moving them (e.g. what does the link to the ecosystems.json file have to do, where do they appear, etc.), but I suspect the workflows.js file might have a reference to the files as well. IIRC these might be the documents that are linked after you select a biome (there is a small PDF link), and that would probably be in the JS file and maybe in a view

As a first step, I think moving these to the `public` folder (probably in a subfolder) & updating those links would make this ticket "done"

If you submit a PR with those changes that would be perfect.

If you run into any problems with setup, please don't hesitate to file it as a new issue. I'd like to make the setup documentation as foolproof as possible, so any lack of clarity on how someone can make this app run locally would be considered a bug to me.

Thanks!

**Comment by VictoriaVasys** [comment]
@jaydorsey thanks for the thorough response! I took some notes while I was setting up & would be happy to open an issue on some trouble I had.
