### ISSUE TITLE
Add config options

### ISSUE THREAD

**Issue by econpotter** [rubyforgood/ghgvc#29]
Add 5 options in a "settings" button and form with the following:

* Anaysis time (T_A): slider ranging from 1-500, default is 50
* Emissions time (T_E): slider ranging from 1-100, default is 50
* Anthropogenic effects (includeANTH): boolean, default is 1
* Biophysical effects (includeBIO): boolean default is 1
* Decay rate (r): slider 0-0.3, default is 0

Select greenhouse gases to include:
* Carbon Dioxide (co2): default checked
* Nitrous Oxide (n20): default checked
* Methane (ch4): default checked

Select sources to include:
* Storage (storage): default checked
* Flux (flux): default checked
* Disturbance (disturbance): default checked

All the above should be variable names in the "options".

**Comment by dlebauer** [comment]
Is this related to https://github.com/ebimodeling/ghgvc/issues/12? It would help to cross-reference the related issues ... 

And would this be a good place to add the option of specifying a location by lat/lon coordinates (https://github.com/ebimodeling/ghgvc/issues/85)?

**Comment by teixeirak** [comment]
Yes, this is related to ebimodeling#12.

**Comment by teixeirak** [comment]
I wouldn't put the lat-long entry here. I will comment on this in ebimodeling#85.

**Comment by teixeirak** [comment]
Can we put a little [?] icon associated with each of these options, with a small text box opens if clicked? I can write a brief explanation of each option. 

Also, lets leave this off the layperson version, if we get around to making it.

**Comment by jaydorsey** [comment]
We can add an icon. I'll open that as a separate issue. Let's discuss how that integrates w/ the layperson version as a separate issue.

Closing this for now since this is merged in.
