### ISSUE TITLE
Modal when "Run Calculator" is pressed not functioning

### ISSUE THREAD

**Issue by jaydorsey** [rubyforgood/ghgvc#48]
The graphic isn't present but the screen does dim. Possibly a lightbox issue.

We're attempting to remove lightbox from the application, so this can be swapped for a native bootstrap modal

Screenshot of original behavior (dim + present below) for reference

![image](https://user-images.githubusercontent.com/191564/27012222-0bb5a784-4e9a-11e7-8d01-74f7c68d4d61.png)

**Comment by liambarstad** [comment]
Hey there, I'm a first time contributor and would love to take a look at this issue. Is the problem still relevant?

**Comment by jaydorsey** [comment]
@liambarstad thanks for reaching out, and welcome! It is still relevant. There's been a few changes to the docker setup, so I'm going to run thru those steps right now and make sure everything is still working

**Comment by jaydorsey** [comment]
@liambarstad I made a few minor updates to the README & confirmed everything should be functional (enough). There's an error on the R server that prevents a valid response from being returned, but that shouldn't affect the display of the modal.

I probably need to add another ticket for displaying an error message when the biome info can't be calculated. Feel free to ping me directly if you run into any issues or have any questions
