### ISSUE TITLE
Add a nice footer to the page

### ISSUE THREAD

**Issue by jaydorsey** [rubyforgood/ghgvc#8]
Currently, no footer exists. Could point back to the repo, possibly the organizations (Smithsonian, UI), etc.

**Comment by stovermc** [comment]
Hi @jaydorsey I have been looking to contribute to an Open Source project and after some searching I wound up in this repo. I have a background in geography with a focus in GIS and climate systems and would love to contribute to this project. Do you mind if I take a stab at this issue? Outside of Smithsonian what other organizations do you have in mind for inclusion in the navbar? Thanks!

**Comment by jaydorsey** [comment]
Welcome to the project @stovermc !

We'd love to have you contribute. For the footer, I think we'll just do the Smithsonian for now but maybe also link back to the main github repo (the one this is forked from). Just getting a footer layout started will be helpful.

FYI I'm out on vacation this week so I may be a little slow to respond until after next weekend. Don't hesitate to grab any ticket that might interest you. 

If you have any issues setting up the environment please feel to file an issue. Also, you might check the other open PRs and issues for solutions (haven't had a chance to integrate yet but will when I get back)

**Comment by jaydorsey** [comment]
Closed with #72
